name: Deploy website
on:
  push:
    branches:
      - main
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          # this is the path for node js for it's internal cache
          # npm builds a cache but since different jobs uses diffeent machines we cannot use this internal cache
          # we tell the npm internal cache to store this on central github server so that it can be used across jobs and workflows
          #key is to fetch the cache Key also will tell if need to re-create the cache if expired 
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
          # the key has a hash based upon the contents of the file. The path is **/package-lock.json files
          # package-lock.json is a listing of all the current dependencies.
          # if anything changes in this file the hash will be different and thus the key will be different and there will have to be a new fetch 
          # to update the cache with the new dependencies listing. There would have to be a reinstall of dependencies
          # npm ci uses this cache. If the cache exists and is to date it will be used.
          # if the cache needs to be re-generated "npm ci" will reinstall all the dependencies.
          # cache steps also executes after job finished so if new dependencies installed it will be updated at end of job
          # extensive listing of use-cases are at https://github.com/actions/cache
          # NOTE: this step must be repeated in all the jobs installing dependencies. Build job will need this too.
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      output-name: ${{ steps.step-id.outputs.output-name }}
      # this is the output of the overall job.
      # the steps is a special context value for github actions
      # it can index the id below by name (step-id, see below)
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          # this is the path for node js for it's internal cache
          # npm builds a cache but since different jobs uses diffeent machines we cannot use this internal cache
          # we tell the npm internal cache to store this on central github server so that it can be used across jobs and workflows
          #key is to fetch the cache Key also will tell if need to re-create the cache if expired 
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
          # the key has a hash based upon the contents of the file. The path is **/package-lock.json files
          # package-lock.json is a listing of all the current dependencies.
          # if anything changes in this file the hash will be different and thus the key will be different and there will have to be a new fetch 
          # to update the cache with the new dependencies listing. There would have to be a reinstall of dependencies
          # npm ci uses this cache. If the cache exists and is to date it will be used.
          # if the cache needs to be re-generated "npm ci" will reinstall all the dependencies.
          # cache steps also executes after job finished so if new dependencies installed it will be updated at end of job
          # extensive listing of use-cases are at https://github.com/actions/cache
          # NOTE: this step must be repeated in all the jobs installing dependencies. Build job will need this too.
          # NOTE: build job will have access to this cache that was initally created in the test job above.  
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
        # this produces artifacts in /dist folder as we saw when running locally
        # the same will happen when the runner runs this 
        # actions/upload-artifact allows us to upload artifacts
      - name: Publish JS filename index.d590f20c.js
        id: step-id
        #id is used above for outputs: output-name above
        run: find dist/assets/*.js -type f -execdir echo 'output-name={}' >> $GITHUB_OUTPUT ';'
        # must generate the name and the output key value pair written to GITHUB_OUTPUT variable
        # 'output-name' is the name used above for the outputs
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        # this will upload the artifacts from the runner
        with:
          name: dist-folder-files
          path: dist
          #name: dist-folder-files
          #path: |
          #  dist
          #  package.json
          #use the pipe for multi-line paths  
  deploy:
  #every job gets a different runner machine so files are not all co-located between jobs
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts from build job
        uses: actions/download-artifact@v3
        # this downloads the artifacts that were uploaded; the download is to the deploy runner
        with:
          name: dist-folder-files
          # grabs the files that were uploaded and downloads them and unzips them
      - name: Output the contents that are on the deploy runner
        run: ls
        #standard linux ls command to show contents of the downloaded folder   
      - name: Output filename
        run: echo "${{ needs.build.outputs.output-name }}" 
        # this command uses the output of the build job data
        # the needs object is required (or the jobs object can be used as well)
        # build is a dependency on this job  
        # this needs object has all the outputs of the build dependency job for this job
      - name: Deploy
        run: echo "Deploying..."
